<%-- 
    Document   : employeeRegistration
    Created on : Mar 6, 2014, 8:29:24 PM
    Author     : bud
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<link rel="stylesheet" href="mainStyle.css" type="text/css" >
<div class="mainContent">
    <h2>Employee Registration</h2>

    <form action="EmployeeServlet" method="post">
        <table>
            <tr>
                <td>Employee Id</td>
                <td><input type="text" name="empId" maxlength="15" placeholder="Autogenerated" disabled=""/></td>
            </tr>
            <tr>
                <td>Employee Name</td>
                <td><input type="text" name="empName" maxlength="45"/></td>
            </tr>
            <tr>
                <td>Department</td>
                <td><input type="text" name="department" maxlength="30"/></td>
            </tr>
            <tr>
                <td>Post</td>
                <td><input type="text" name="post" maxlength="30"/></td>
            </tr>
            <tr>
                <td>Salary</td>
                <td><input type="text" name="salary" maxlength="8"/></td>
            </tr>
            <tr>
                <td>Gender</td>
                <td><input type="radio" name="gender" value="Male"/>Male
                    <input type="radio" name="gender" value="Female"/>Female</td>
            </tr>
            <tr>
                <td>Age</td>
                <td><input type="text" name="age" maxlength="3"/></td>
            </tr>
            <tr>
                <td>Join Date</td>
                <td><input type="text" name="joinDate"/></td>
            </tr>
            <tr>
                <td>Email</td>
                <td><input type="email" name="email"/></td>
            </tr>
            <tr>
                <td style="text-align: center;"><input type="reset" value="Reset Form"/></td>
                <td style="text-align: center;"><input type="submit" value="Register" name="addEmployee"/></td>
            </tr>
        </table>
    </form>
</div>